### PR TITLE
upgrade dependencies requirejs to latest stable version

### PR DESCRIPTION
**Pull request by zhangchiqing**
Upgrade `requirejs` to 2.1.15 to fix https://github.com/Automattic/socket.io-client/issues/690

screen shot 2014-11-05 at 09 54 11

### CODE REVIEW

**Comment by juanmaia** [comment]
wtf? the guy abandoned the repo

**Comment by jorrit** [comment]
They have been updated in the last couple of commits. Could you all try the current git version to see if it now works for you?

**Comment by jorrit** [comment]
File size change report for this build:
bin/pr-filesize-reporter.js: 22 B (new)

**Comment by jorrit** [comment]
File size change report for this build:

bin/pr-filesize-reporter.js: 22 B (new)

**Pull request closed without merging**
